#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "garden-party"
name = "Garden Party"
description.en = "Help gardening newbies to manage their garden"

version = "0.19.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
website = "https://garden-party.io/"
demo = "https://garden-party.experimentslabs.com/"
admindoc = "https://doc.garden-party.io/"
code = "https://gitlab.com/experimentslabs/garden-party/garden-party"

[integration]
yunohost = ">= 12.1.22"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "500M"
ram.build = "5G"
ram.runtime = "300M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gardenparty"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://gitlab.com/api/v4/projects/22733551/packages/generic/slim-build/0.19.0/garden-party-0.19.0.tar.gz"
    sha256 = "c68201b6180a86d40badbcaac13217c650f04ed2145bda689ae6ddd9f0204199"
    extract   = true

    autoupdate.strategy = "latest_gitlab_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = [
        # Dabatases dependencies
        "postgresql", "redis-server",     
        # Ruby dependencies
        "libjemalloc-dev", "libffi-dev", "libyaml-dev", "zlib1g-dev", 
        # Other dependencies
        "libvips42", "libpq-dev",
        "libpq-dev", "libyaml-dev", "libxml2-dev",
    ]

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "20.15.1"

    [resources.ruby]
    version = "3.3.8"
